-- 生成的SQL语句用于导入项目数据（第2部分）
-- 执行时间：2025-07-27

-- 导入项目数据（续）
INSERT INTO projects (name, code) VALUES
('ZUS Coffee', 'zuscoffee'),
('Tour Card', 'tourcard'),
('歡歌', 'huange'),
('RO仙境傳說', 'ro'),
('古怪加速器', 'guguai'),
('PopChill', 'popchill'),
('伴迪', 'bandi'),
('DiGeam', 'digeam'),
('Soup', 'soup'),
('WeFun', 'wefun'),
('FoneApp', 'foneapp'),
('分分有禮', 'fenfen'),
('Nicee', 'nicee'),
('MChat', 'mchat'),
('BFMessenger', 'bfmessenger'),
('小鹿茶', 'xiaolucha'),
('Alipay password', 'alipaypass'),
('dobiQueen', 'dobiqueen'),
('CSFACE', 'csface'),
('華義', 'huayi'),
('mclcinema', 'mclcinema'),
('Noones', 'noones'),
('bingoplus.com', 'bingoplus'),
('arenaplus', 'arenaplus'),
('QRPay', 'qrpay'),
('Coolblog', 'coolblog'),
('QPP', 'qpp'),
('野蠻世界娛樂城', 'yeman'),
('inboxdollars', 'inboxdollars'),
('Global Cash / 全球付', 'globalcash'),
('华润通', 'huaruntong'),
('点万象', 'dianwanxiang'),
('iGameBUY', 'igamebuy'),
('OPPO', 'oppo'),
('litmatch', 'litmatch'),
('MyCard', 'mycard'),
('Talabat', 'talabat'),
('FIVE Petrol', 'fivepetrol'),
('LUUP', 'luup'),
('GOApp', 'goapp'),
('Game One', 'gameone'),
('TauKe', 'tauke'),
('DANA', 'dana'),
('HDI', 'hdi'),
('绿洲', 'lvzhou'),
('FitStats', 'fitstats'),
('87MS', '87ms'),
('汽水音乐', 'qishui'),
('redBus', 'redbus'),
('ZeroGame', 'zerogame'),
('bigwin888', 'bigwin888'),
('cashbet777', 'cashbet777'),
('flypgs', 'flypgs'),
('吉祥航空', 'jixiang'),
('BetWay', 'betway'),
('MosTalk', 'mostalk'),
('Tandoo / 超神数据', 'tandoo'),
('吉野家', 'jiyejia'),
('ゲームトレード', 'gametrade'),
('holdcover', 'holdcover'),
('Bibo', 'bibo'),
('AR Lens', 'arlens'),
('LiveMe / 快验证', 'liveme'),
('bluahealth', 'bluahealth'),
('悟空', 'wukong'),
('有柿', 'youshi'),
('掘夢網', 'juemeng'),
('TopOne', 'topone'),
('澳門童星大賽', 'aomen'),
('S Go', 'sgo'),
('未闻网络', 'weiwen'),
('TRYKE', 'tryke'),
('Gigi Coffee', 'gigicoffee'),
('myNEWS', 'mynews'),
('汽车之家', 'qichezj'),
('Teambition', 'teambition'),
('bet4cuci', 'bet4cuci'),
('Twilio', 'twilio'),
('Drops of Fun', 'dropsoffun'),
('Flip', 'flip'),
('Authy', 'authy'),
('北京环球', 'bjhq'),
('LifePoints', 'lifepoints'),
('115科技', '115tech'),
('Ipsos iSay', 'ipsosisay'),
('Alchemy', 'alchemy'),
('wins88', 'wins88'),
('FB SHOP / 台塑生醫', 'fbshop'),
('cinema.com', 'cinema'),
('Next Idol', 'nextidol'),
('Pizza Hut', 'pizzahut'),
('抖音商城', 'dysc'),
('CCG HEARTS', 'ccghearts'),
('Pacific Coffee', 'pacificcoffee'),
('Access to web', 'accessweb'),
('Powerbuy', 'powerbuy'),
('发短信测试项目', 'smstest'),
('红果短剧', 'hongguo'),
('ICE CREAM', 'icecream'),
('binfinite', 'binfinite'),
('秒投', 'miaotou'),
('yuu', 'yuu'),
('小工藝家', 'xiaogongyi'),
('TMTW / TIXCRAFT.COM', 'tmtw'),
('高德地图', 'gaode'),
('LIFETASTIC', 'lifetastic'),
('mg5 / mangot5', 'mg5'),
('Chubb Life', 'chubblife'),
('Valued Opinions', 'valuedopinions'),
('Qantas', 'qantas'),
('EleLive', 'elelive'),
('tujia', 'tujia'),
('flysas.com / SAS', 'flysas'),
('途风', 'tufeng'),
('Storellet', 'storellet'),
('591搵樓', '591'),
('帮和 / bhe', 'banghe'),
('香港高登討論區', 'hkgolden'),
('BusOnlineTicket', 'busonline'),
('海豚加速器', 'haitun'),
('SerpApi', 'serpapi'),
('MyACUVUE', 'myacuvue'),
('RE', 're'),
('德扑之星 / Poker Stars', 'pokerstars'),
('极氪', 'jike'),
('沃尔玛 / Walmart', 'walmart'),
('ZhipuAI', 'zhipuai'),
('boclife', 'boclife'),
('omne', 'omne'),
('KBX', 'kbx'),
('王者营地', 'wangzhe'),
('Greywoods', 'greywoods'),
('SUBMAIL', 'submail'),
('雅培', 'yabei'),
('intelcupid / 她说', 'intelcupid'),
('Fantopia', 'fantopia'),
('Presto', 'presto'),
('the L', 'thel2'),
('Doorverse', 'doorverse'),
('ALY', 'aly'),
('Vingobet', 'vingobet'),
('澳門電召', 'aomendz'),
('PPAP', 'ppap'),
('Steemit', 'steemit'),
('azgo', 'azgo'),
('MosApp', 'mosapp'),
('HKairport Rewards', 'hkairport'),
('Peach', 'peach'),
('azurlane / 碧藍航線', 'azurlane'),
('Cuci Express', 'cuciexpress'),
('CLUB99 / AMWAY', 'club99'),
('火花Chat', 'huohua'),
('OK 齊齊印', 'okqiqi'),
('阿里商旅', 'alishanglv'),
('云汉芯城', 'yunhan'),
('Google RCS', 'googlercs'),
('Radquest', 'radquest'),
('Wesing', 'wesing'),
('EGS', 'egs'),
('CSDN', 'csdn'),
('growtopia', 'growtopia'),
('德谱', 'depu'),
('SoFi', 'sofi'),
('zenonia / 戰界', 'zenonia'),
('UMobile', 'umobile'),
('VITASOY', 'vitasoy'),
('360Kredi', '360kredi'),
('Garena', 'garena'),
('Ninjaz', 'ninjaz'),
('美柚', 'meiyou'),
('Ticket Plus', 'ticketplus'),
('Cosmart / 科斯玛特', 'cosmart'),
('Go Noodle House', 'gonoodle'),
('豆包MarsCode', 'marscode'),
('SayHi Chat', 'sayhichat'),
('Harry APP', 'harryapp'),
('USERJOY', 'userjoy'),
('goodniight', 'goodniight'),
('Empire88', 'empire88'),
('MEEFF', 'meeff'),
('FanShu', 'fanshu'),
('洋葱学园', 'yangcong'),
('DHL', 'dhl'),
('极光TV', 'jiguangtv'),
('jag-hk', 'jaghk'),
('Power Ship', 'powership'),
('WAUG', 'waug'),
('Shell Asia', 'shellasia'),
('Club 100', 'club100'),
('香港討論區', 'hkdiscuss'),
('Perya', 'perya'),
('职业培训网络平台', 'zhiyepx'),
('opinionworld', 'opinionworld'),
('MRG', 'mrg'),
('Sendo', 'sendo'),
('阅文集团', 'yuewen'),
('Vnptt', 'vnptt'),
('ClassPass', 'classpass'),
('悠悠优品 / youpin', 'youpin'),
('VIENDONG', 'viendong'),
('Peryagame', 'peryagame'),
('中国平安', 'pingan'),
('DCFever', 'dcfever'),
('GASH', 'gash'),
('ChoTot', 'chotot'),
('dito.ph', 'dito'),
('智联', 'zhilian'),
('抖音搜索', 'dysearch'),
('FunTown (戲谷)', 'funtown'),
('weed.th', 'weedth'),
('PlayTime', 'playtime'),
('Sparklive / Uplive', 'sparklive'),
('エディオン(edion)', 'edion'),
('circlek.hk', 'circlek'),
('Tealive', 'tealive'),
('TRYLINK', 'trylink'),
('IntBell', 'intbell'),
('Pepsi', 'pepsi'),
('TASKAL', 'taskal'),
('mercari', 'mercari'),
('gameonevn', 'gameonevn'),
('BUYandSHIP', 'buyandship'),
('Konvy', 'konvy'),
('GameZone', 'gamezone'),
('天虹', 'tianhong'),
('澳門售票網', 'aomenpiao'),
('MetaLive', 'metalive'),
('TrueID', 'trueid'),
('TakerVN', 'takervn'),
('Jardin Coffee', 'jardincoffee'),
('LINK UP', 'linkup'),
('九优', 'jiuyou'),
('Coinpayu', 'coinpayu'),
('出会 1500', 'deai1500'),
('快乐邮件', 'kuaileyoujian'),
('メル☆パラ', 'merupara'),
('Jメール', 'jmail'),
('inf', 'inf'),
('玛丽', 'mali'),
('小象超市', 'xiaoxiang'),
('cuddle', 'cuddle'),
('Electronics Extreme', 'electronicsextreme'),
('the1', 'the1'),
('Swensens', 'swensens'),
('永辉生活', 'yonghui'),
('BopLive', 'boplive'),
('山姆網購', 'sams'),
('航班管家', 'hangban'),
('智谱清言', 'zhipuqingyan'),
('ANW', 'anw'),
('Rakuten', 'rakuten'),
('T-pop', 'tpop'),
('ZaloPay', 'zalopay'),
('Payoo', 'payoo'),
('盛趣游戏', 'shengqu'),
('Mocamoca', 'mocamoca'),
('丝瓜', 'sigua'),
('豆瓣网', 'douban'),
('Lushvibe', 'lushvibe'),
('Payment', 'payment'),
('票星球', 'piaoxingqiu'),
('STS', 'sts'),
('CQ', 'cq'),
('Dino', 'dino'),
('CHAGEE', 'chagee'),
('尚耐科技', 'shangnai'),
('WeCom', 'wecom'),
('KTSP', 'ktsp'),
('Eskimo', 'eskimo'),
('唯客/ weex', 'weex'),
('QINIU', 'qiniu'),
('LORDNINE', 'lordnine'),
('bc.game', 'bcgame'),
('HASH_GO', 'hashgo'),
('Dcard', 'dcard'),
('TELUS', 'telus'),
('贝壳找房', 'beike'),
('Met', 'met'),
('piccoma', 'piccoma'),
('sayweee', 'sayweee'),
('Telz', 'telz'),
('ybirds', 'ybirds'),
('AlipayHK', 'alipayhk'),
('金光华广场', 'jinguanghua'),
('lifecard', 'lifecard'),
('idare', 'idare'),
('ANA X', 'anax'),
('MacauTicket', 'macauticket'),
('Wellcome', 'wellcome'),
('DASH', 'dash'),
('599体育', '599sports'),
('2hungry', '2hungry'),
('Pokemoncenter', 'pokemoncenter'),
('K8', 'k8'),
('L7', 'l7'),
('WW / ワクワク', 'ww'),
('STARCG', 'starcg'),
('ICWPSW', 'icwpsw'),
('hachi-pay', 'hachipay'),
('恋爱物语', 'lianai'),
('火箭分享會', 'huojian'),
('On-us', 'onus'),
('ManulifeHK', 'manulifehk'),
('GALAXY / 麦座', 'galaxy'),
('乐道', 'ledao'),
('抖店', 'doudian'),
('巨量引擎', 'juliang'),
('爱看', 'aikan'),
('iQOO', 'iqoo'),
('壹信', 'yixin'),
('菜鸟 / cainiao', 'cainiao'),
('搜狐', 'souhu'),
('Wasai', 'wasai'),
('优速通', 'yousutong'),
('SOGO', 'sogo'),
('kaosmileclub', 'kaosmile'),
('Marrybrown', 'marrybrown'),
('centralx', 'centralx'),
('Meitu', 'meitu'),
('FamilyMart', 'familymart'),
('betman378', 'betman378'),
('积目', 'jimu'),
('Watson', 'watson'),
('苏宁易购', 'suning'),
('OneForma', 'oneforma'),
('DailyCoffee', 'dailycoffee'),
('盼游网', 'panyou'),
('SeoulPass', 'seoulpass'),
('pj88', 'pj88'),
('KK/kikonclub', 'kikonclub'),
('2-Step', '2step'),
('EFSANE', 'efsane'),
('Cosway', 'cosway'),
('Pazzy', 'pazzy'),
('HiFun', 'hifun'),
('With', 'with'),
('karrot / キャロット', 'karrot'),
('PNS網購', 'pns'),
('游戏橘子', 'youxijuzi'),
('ibon', 'ibon'),
('HKTicketing', 'hkticket'),
('佳元 / Jiayuan', 'jiayuan'),
('Beutea', 'beutea'),
('雷蛇 / Razer', 'razer'),
('盛世壹號', 'shengshi'),
('澳門航空', 'aomenair'),
('magi', 'magi'),
('swerte88', 'swerte88'),
('jilino1', 'jilino1'),
('Milyon88', 'milyon88'),
('BETSO88', 'betso88'),
('PuluPeso', 'pulupeso'),
('ASOBO', 'asobo'),
('东方航空', 'dongfang'),
('tcccfrs', 'tcccfrs'),
('SIGOIntOTP', 'sigointotp'),
('WowPera', 'wowpera'),
('大家減齡 Live Young', 'liveyoung'),
('AU PAY', 'aupay'),
('mf CAsh', 'mfcash'),
('MapPraise', 'mappraise'),
('迅游网络', 'xunyou'),
('Boost', 'boost'),
('瑞幸咖啡 / luckin coffee', 'lc'),
('OlduBil', 'oldubil'),
('CloudChat', 'cloudchat'),
('KLOOK', 'kl'),
('得到', 'dedao'),
('MosGram', 'mosgram'),
('阿里巴巴钉钉', 'dingtalk');
