-- 生成的SQL语句用于导入国家和项目数据
-- 执行时间：2025-07-27

-- 清空countries表
DELETE FROM countries;

-- 导入国家数据
INSERT INTO countries (name, code, phone_code) VALUES
('中国', 'cn', '+86'),
('香港', 'hk', '+852'),
('台湾', 'tw', '+886'),
('美国', 'us', '+1'),
('英国', 'gb', '+44'),
('俄罗斯', 'ru', '+7'),
('乌克兰', 'ua', '+380'),
('哈萨克斯坦', 'kz', '+7'),
('印度尼西亚', 'id', '+62'),
('马来西亚', 'my', '+60'),
('菲律宾', 'ph', '+63'),
('缅甸', 'mm', '+95'),
('越南', 'vn', '+84'),
('泰国', 'th', '+66'),
('印度', 'in', '+91'),
('巴基斯坦', 'pk', '+92'),
('肯尼亚', 'ke', '+254'),
('坦桑尼亚', 'tz', '+255'),
('吉尔吉斯斯坦', 'kg', '+996'),
('以色列', 'il', '+972'),
('德国', 'de', '+49'),
('法国', 'fr', '+33'),
('意大利', 'it', '+39'),
('西班牙', 'es', '+34'),
('葡萄牙', 'pt', '+351'),
('荷兰', 'nl', '+31'),
('比利时', 'be', '+32'),
('瑞典', 'se', '+46'),
('挪威', 'no', '+47'),
('芬兰', 'fi', '+358'),
('丹麦', 'dk', '+45'),
('波兰', 'pl', '+48'),
('奥地利', 'at', '+43'),
('瑞士', 'ch', '+41'),
('希腊', 'gr', '+30'),
('土耳其', 'tr', '+90'),
('埃及', 'eg', '+20'),
('南非', 'za', '+27'),
('尼日利亚', 'ng', '+234'),
('墨西哥', 'mx', '+52'),
('巴西', 'br', '+55'),
('阿根廷', 'ar', '+54'),
('智利', 'cl', '+56'),
('哥伦比亚', 'co', '+57'),
('秘鲁', 'pe', '+51'),
('委内瑞拉', 've', '+58'),
('加拿大', 'ca', '+1'),
('澳大利亚', 'au', '+61'),
('新西兰', 'nz', '+64'),
('日本', 'jp', '+81'),
('韩国', 'kr', '+82'),
('新加坡', 'sg', '+65'),
('阿联酋', 'ae', '+971'),
('沙特阿拉伯', 'sa', '+966'),
('卡塔尔', 'qa', '+974');

-- 清空projects表
DELETE FROM projects;

-- 导入项目数据
INSERT INTO projects (name, code) VALUES
('Telegram (TG) / (飞机)', 'tg'),
('Instagram', 'ig'),
('Google / Gmail (谷歌)', 'go'),
('Facebook(脸书)', 'fb'),
('WhatsApp / WS', 'wa'),
('WeChat 微信', 'wc'),
('QQ', 'qq'),
('Taobao (淘宝)', 'tb'),
('JD.com 京东', 'jd'),
('Pinduoduo (拼多多)', 'pdd'),
('Bilibili (哔哩哔哩)', 'bl'),
('Xiaohongshu (小红书 / RED)', 'xhs'),
('Kuaishou (快手科技)', 'ks'),
('Tiktok (抖音)', 'tk'),
('Discord', 'dc'),
('Yahoo', 'ya'),
('Yahoo2 (雅虎)', 'ya2'),
('VKcom', 'vk'),
('Plenty of Fish (POF)', 'pof'),
('Tinder', 'td'),
('Baidu (百度)', 'bd'),
('Nimo TV', 'nimo'),
('Nike', 'nike'),
('JD Dating (JD交友)', 'jdd'),
('Amazon (亚马逊)', 'am'),
('Amazon AWS', 'aws'),
('Microsoft Azure / AOL', 'azure'),
('Blued', 'blued'),
('Bumble', 'bm'),
('Foodpanda', 'fp'),
('Hinge', 'hg'),
('Kakaotalk', 'kk'),
('LINE', 'li'),
('Coffee Meets Bagel / CMB', 'cmb'),
('MapleSEA', 'maple'),
('Michat', 'michat'),
('Omiai', 'omiai'),
('OkCupid', 'ok'),
('Outlook 邮箱', 'ol'),
('Potato (土豆)', 'potato'),
('Paypal', 'pp'),
('Shopee', 'sp'),
('Skout', 'skout'),
('SoulAPP', 'soul'),
('SweetRing', 'sweet'),
('TapTap', 'taptap'),
('Twitter (推特) X', 'tw'),
('Uber', 'ub'),
('WeDate', 'wedate'),
('WePlay', 'weplay'),
('Wish', 'wish'),
('ZCity', 'zcity'),
('Zalo', 'zl'),
('DewuPoison (得物App)', 'dewu'),
('Naver', 'naver'),
('NetEase (网易)', 'ne'),
('Letstalk', 'letstalk'),
('Tantan (探探)', 'tn'),
('TNG eWallet', 'tng'),
('Omi', 'omi'),
('Blizzard（暴雪）', 'bz'),
('Alipay (支付宝)', 'ap'),
('Beanfun / GamaniaHK', 'beanfun'),
('Nico', 'nico'),
('Yueme', 'yueme'),
('SpeedyLoving (速約)', 'speedy'),
('Viber', 'vi'),
('Batchat (蝙蝠注册)', 'batchat'),
('QuickPass (云闪付)', 'quickpass'),
('CAMS充电', 'cams'),
('GeeGee', 'geegee'),
('Carousell', 'carousell'),
('Her', 'her'),
('LesPark', 'lespark'),
('MoneyBack', 'moneyback'),
('Octopus (八達通)', 'octopus'),
('小米有品', 'xy'),
('APPLE / 苹果', 'apl'),
('TALK2ALL', 'talk2all'),
('Weibo (微博)', 'wb'),
('浪Live', 'langlive'),
('Weipaitang (微拍堂)', 'weipaitang'),
('Zoho', 'zh'),
('Gratus', 'gratus'),
('Hello BiBi', 'hellobibi'),
('ParPar', 'parpar'),
('拍住赏', 'paizhu'),
('Setel', 'setel'),
('SIGNAL', 'sg'),
('MOVIDER', 'movider'),
('Candy (糖果口袋)', 'candy'),
('Survey', 'survey'),
('Aurora', 'aurora'),
('PDlive / POYO', 'pdlive'),
('Momo (陌陌科技)', 'mm'),
('OpenAI / ChatGpt', 'oa'),
('DianPing (大众点评)', 'dianping'),
('RICHDADDY', 'richdaddy'),
('Kakao', 'kakao'),
('JKF', 'jkf'),
('V SHOW', 'vshow'),
('BroadBlue', 'broadblue'),
('GODA LIVE', 'godalive'),
('Duoshan (多闪)', 'duoshan'),
('Minima', 'minima'),
('NikeHK', 'nikehk'),
('MonChats', 'monchats'),
('千图', 'qiantu'),
('BCD / blackcard', 'bcd'),
('DiDi / 滴滴', 'dd'),
('Rooit', 'rooit'),
('5EPLAY (5E对战平台)', '5e'),
('Adidas', 'adidas'),
('A.V.A 戰地之王', 'ava'),
('Heymandi', 'heymandi'),
('Yippi', 'yippi'),
('BeeBar', 'beebar'),
('Wahgoods', 'wahgoods'),
('ProtonMail', 'pm'),
('Pong Pong', 'pongpong'),
('Lizhi FM', 'lizhi'),
('Meituan (美团）', 'mt'),
('Palip', 'palip'),
('Huawei / 华为', 'hw'),
('LianSheng', 'liansheng'),
('PerfectWorld (完美世界)', 'pw'),
('HKTVmall', 'hktvmall'),
('imgoTV', 'imgotv'),
('Fantuan Delivery (饭团外卖)', 'ft'),
('小芒app (XIAOMANG)', 'xiaomang'),
('OffGamers', 'offgamers'),
('GNJOY', 'gnjoy'),
('Fanhouse', 'fanhouse'),
('eBay', 'eb'),
('同程旅行', 'tongcheng'),
('LinkedIn', 'ln'),
('Hermes (爱马仕)', 'hermes'),
('VeryKuai (加速器)', 'verykuai'),
('腾讯科技', 'tx'),
('折耳', 'zheer'),
('沃畅连', 'wochanglian'),
('BitMEX', 'bitmex'),
('Yandex', 'yx'),
('ArtPro', 'artpro'),
('VERIFY', 'verify'),
('G2G', 'g2g'),
('Rumble', 'rumble'),
('PUBG', 'pg'),
('Virbox', 'virbox'),
('Tule', 'tule'),
('Givingli', 'givingli'),
('Microsoft Partner Network', 'mspartner'),
('VIVO', 'vivo'),
('Bolt', 'bt'),
('Bondora', 'bondora'),
('Revolut', 'revolut'),
('Unacademy', 'unacademy'),
('Clubhouse', 'ch'),
('Numero eSIM', 'numero'),
('Tango', 'tg2'),
('Ticketmaster', 'ticketmaster'),
('Getir', 'getir'),
('Hago', 'hago'),
('Depop', 'depop'),
('Coinbase', 'cb'),
('Twig', 'twig'),
('pCloudy', 'pcloudy'),
('ToTok', 'totok'),
('Samsung', 'samsung'),
('MingPeng', 'mingpeng'),
('Num2', 'num2'),
('Boyaa', 'boyaa'),
('PayBy', 'payby'),
('Yalla', 'yalla'),
('Rewire', 'rewire'),
('Sendwave', 'sendwave'),
('Baboon', 'baboon'),
('Dundle', 'dundle'),
('OYO', 'oyo'),
('OKru', 'okru'),
('MeWe', 'mw'),
('Hanabi', 'hanabi'),
('OpenRice', 'openrice'),
('Ayoba', 'ayoba'),
('This Fate', 'thisfate'),
('Alibaba （阿里巴巴）', 'alibaba'),
('Hertz （赫兹）', 'hertz'),
('Yubo', 'yubo'),
('YY', 'yy'),
('Xigua Video （西瓜视频）', 'xigua'),
('Toutiao （今日头条）', 'toutiao'),
('OKX', 'okx'),
('Thai Life (泰国人寿)', 'thailife'),
('Douyu (斗鱼)', 'douyu'),
('Huya (虎牙)', 'huya'),
('Douban (豆瓣)', 'douban'),
('Zhihu (知乎)', 'zhihu'),
('Meituan (美团)', 'meituan'),
('Didi (滴滴)', 'didi'),
('Ctrip (携程)', 'ctrip'),
('Ele.me (饿了么)', 'eleme'),
('Youku (优酷)', 'youku'),
('iQiyi (爱奇艺)', 'iqiyi'),
('Tencent Video (腾讯视频)', 'tencentvideo'),
('Tencent Music (腾讯音乐)', 'tencentmusic'),
('NetEase Cloud Music (网易云音乐)', 'netease'),
('Sina Weibo (新浪微博)', 'weibo'),
('Baidu Tieba (百度贴吧)', 'tieba'),
('Baidu Map (百度地图)', 'baidumap'),
('Alipay (支付宝)', 'alipay'),
('WeChat Pay (微信支付)', 'wechatpay'),
('UnionPay (银联)', 'unionpay'),
('JD Finance (京东金融)', 'jdfinance'),
('Ant Fortune (蚂蚁财富)', 'antfortune'),
('Tencent News (腾讯新闻)', 'tencentnews'),
('Sina News (新浪新闻)', 'sinanews'),
('Sohu News (搜狐新闻)', 'sohunews'),
('NetEase News (网易新闻)', 'neteasenews'),
('Baidu News (百度新闻)', 'baidunews'),
('QQ Music (QQ音乐)', 'qqmusic'),
('QQ Mail (QQ邮箱)', 'qqmail'),
('QQ Browser (QQ浏览器)', 'qqbrowser'),
('QQ Space (QQ空间)', 'qzone'),
('Tencent Meeting (腾讯会议)', 'tencentmeeting'),
('Tencent Docs (腾讯文档)', 'tencentdocs'),
('Tencent Cloud (腾讯云)', 'tencentcloud'),
('Alibaba Cloud (阿里云)', 'alicloud'),
('Baidu Cloud (百度云)', 'baiducloud'),
('Huawei Cloud (华为云)', 'huaweicloud'),
('Tencent WeChat (腾讯微信)', 'wechat'),
('Tencent WeChat Work (企业微信)', 'wechatwork'),
('DingTalk (钉钉)', 'dingtalk'),
('Feishu (飞书)', 'feishu'),
('Maimai (脉脉)', 'maimai'),
('Boss Zhipin (BOSS直聘)', 'bosszhipin'),
('Zhaopin (智联招聘)', 'zhaopin'),
('51job (前程无忧)', '51job'),
('Lagou (拉勾)', 'lagou'),
('Liepin (猎聘)', 'liepin'),
('Didi Chuxing (滴滴出行)', 'didichuxing'),
('Hellobike (哈啰出行)', 'hellobike'),
('Meituan Bike (美团单车)', 'meituanbike'),
('Gaode Map (高德地图)', 'gaodemap'),
('Tencent Map (腾讯地图)', 'tencentmap'),
('Qunar (去哪儿)', 'qunar'),
('Fliggy (飞猪)', 'fliggy'),
('Mafengwo (马蜂窝)', 'mafengwo'),
('Tuniu (途牛)', 'tuniu'),
('eLong (艺龙)', 'elong'),
('Koubei (口碑)', 'koubei'),
('Hema (盒马)', 'hema'),
('JD Daojia (京东到家)', 'jddaojia'),
('Meituan Waimai (美团外卖)', 'meituanwaimai'),
('Eleme Waimai (饿了么外卖)', 'elemewaimai'),
('Tmall (天猫)', 'tmall'),
('Vipshop (唯品会)', 'vipshop'),
('Suning (苏宁易购)', 'suning'),
('Gome (国美)', 'gome'),
('Dangdang (当当)', 'dangdang'),
('Amazon China (亚马逊中国)', 'amazonchina'),
('Kaola (考拉海购)', 'kaola'),
('Mogujie (蘑菇街)', 'mogujie'),
('Meilishuo (美丽说)', 'meilishuo'),
('Jumei (聚美优品)', 'jumei'),
('Yihaodian (1号店)', 'yihaodian'),
('Xiaomi (小米)', 'xiaomi'),
('Oppo', 'oppo'),
('Lenovo (联想)', 'lenovo'),
('ZTE (中兴)', 'zte'),
('Meizu (魅族)', 'meizu'),
('OnePlus (一加)', 'oneplus'),
('Realme', 'realme'),
('Honor (荣耀)', 'honor'),
('Nubia (努比亚)', 'nubia'),
('Smartisan (锤子)', 'smartisan'),
('Gionee (金立)', 'gionee'),
('Coolpad (酷派)', 'coolpad'),
('TCL', 'tcl'),
('ZUS Coffee', 'zuscoffee'),
('Tour Card', 'tourcard'),
('歡歌', 'huange'),
('RO仙境傳說', 'ro'),
('古怪加速器', 'guguai'),
('PopChill', 'popchill'),
('伴迪', 'bandi'),
('DiGeam', 'digeam'),
('Soup', 'soup'),
('WeFun', 'wefun'),
('FoneApp', 'foneapp'),
('分分有禮', 'fenfen'),
('Nicee', 'nicee'),
('MChat', 'mchat'),
('BFMessenger', 'bfmessenger'),
('小鹿茶', 'xiaolucha'),
('Alipay password', 'alipaypass'),
('dobiQueen', 'dobiqueen'),
('CSFACE', 'csface'),
('華義', 'huayi'),
('mclcinema', 'mclcinema'),
('Noones', 'noones'),
('bingoplus.com', 'bingoplus'),
('arenaplus', 'arenaplus'),
('QRPay', 'qrpay'),
('Coolblog', 'coolblog'),
('QPP', 'qpp'),
('野蠻世界娛樂城', 'yeman'),
('inboxdollars', 'inboxdollars'),
('Global Cash / 全球付', 'globalcash'),
('华润通', 'huaruntong'),
('点万象', 'dianwanxiang'),
('iGameBUY', 'igamebuy'),
('OPPO', 'oppo'),
('litmatch', 'litmatch'),
('MyCard', 'mycard'),
('Talabat', 'talabat'),
('FIVE Petrol', 'fivepetrol'),
('LUUP', 'luup'),
('GOApp', 'goapp'),
('Game One', 'gameone'),
('TauKe', 'tauke'),
('DANA', 'dana'),
('HDI', 'hdi'),
('绿洲', 'lvzhou'),
('FitStats', 'fitstats'),
('87MS', '87ms'),
('汽水音乐', 'qishui'),
('redBus', 'redbus'),
('ZeroGame', 'zerogame'),
('bigwin888', 'bigwin888'),
('cashbet777', 'cashbet777'),
('flypgs', 'flypgs'),
('吉祥航空', 'jixiang'),
('BetWay', 'betway'),
('MosTalk', 'mostalk'),
('Tandoo / 超神数据', 'tandoo'),
('吉野家', 'jiyejia'),
('ゲームトレード', 'gametrade'),
('holdcover', 'holdcover'),
('Bibo', 'bibo'),
('AR Lens', 'arlens'),
('LiveMe / 快验证', 'liveme'),
('bluahealth', 'bluahealth'),
('悟空', 'wukong'),
('有柿', 'youshi'),
('掘夢網', 'juemeng'),
('TopOne', 'topone'),
('澳門童星大賽', 'aomen'),
('S Go', 'sgo'),
('未闻网络', 'weiwen'),
('TRYKE', 'tryke'),
('Gigi Coffee', 'gigicoffee'),
('myNEWS', 'mynews'),
('汽车之家', 'qichezj'),
('Teambition', 'teambition'),
('bet4cuci', 'bet4cuci'),
('Twilio', 'twilio'),
('Drops of Fun', 'dropsoffun'),
('Flip', 'flip'),
('Authy', 'authy'),
('北京环球', 'bjhq'),
('LifePoints', 'lifepoints'),
('115科技', '115tech'),
('Ipsos iSay', 'ipsosisay'),
('Alchemy', 'alchemy'),
('wins88', 'wins88'),
('FB SHOP / 台塑生醫', 'fbshop'),
('cinema.com', 'cinema'),
('Next Idol', 'nextidol'),
('Pizza Hut', 'pizzahut'),
('抖音商城', 'dysc'),
('CCG HEARTS', 'ccghearts'),
('Pacific Coffee', 'pacificcoffee'),
('Access to web', 'accessweb'),
('Powerbuy', 'powerbuy'),
('发短信测试项目', 'smstest'),
('红果短剧', 'hongguo'),
('ICE CREAM', 'icecream'),
('binfinite', 'binfinite'),
('秒投', 'miaotou'),
('yuu', 'yuu'),
('小工藝家', 'xiaogongyi'),
('TMTW / TIXCRAFT.COM', 'tmtw'),
('高德地图', 'gaode'),
('LIFETASTIC', 'lifetastic'),
('mg5 / mangot5', 'mg5'),
('Chubb Life', 'chubblife'),
('Valued Opinions', 'valuedopinions'),
('Qantas', 'qantas'),
('EleLive', 'elelive'),
('tujia', 'tujia'),
('flysas.com / SAS', 'flysas'),
('途风', 'tufeng'),
('Storellet', 'storellet'),
('591搵樓', '591'),
('帮和 / bhe', 'banghe'),
('香港高登討論區', 'hkgolden'),
('BusOnlineTicket', 'busonline'),
('海豚加速器', 'haitun'),
('SerpApi', 'serpapi'),
('MyACUVUE', 'myacuvue'),
('RE', 're'),
('德扑之星 / Poker Stars', 'pokerstars'),
('极氪', 'jike'),
('沃尔玛 / Walmart', 'walmart'),
('ZhipuAI', 'zhipuai'),
('boclife', 'boclife'),
('omne', 'omne'),
('KBX', 'kbx'),
('王者营地', 'wangzhe'),
('Greywoods', 'greywoods'),
('SUBMAIL', 'submail'),
('雅培', 'yabei'),
('intelcupid / 她说', 'intelcupid'),
('Fantopia', 'fantopia'),
('Presto', 'presto'),
('the L', 'thel2'),
('Doorverse', 'doorverse'),
('ALY', 'aly'),
('Vingobet', 'vingobet'),
('澳門電召', 'aomendz'),
('PPAP', 'ppap'),
('Steemit', 'steemit'),
('azgo', 'azgo'),
('MosApp', 'mosapp'),
('HKairport Rewards', 'hkairport'),
('Peach', 'peach'),
('azurlane / 碧藍航線', 'azurlane'),
('Cuci Express', 'cuciexpress'),
('CLUB99 / AMWAY', 'club99'),
('火花Chat', 'huohua'),
('OK 齊齊印', 'okqiqi'),
('阿里商旅', 'alishanglv'),
('云汉芯城', 'yunhan'),
('Google RCS', 'googlercs'),
('Radquest', 'radquest'),
('Wesing', 'wesing'),
('EGS', 'egs'),
('CSDN', 'csdn'),
('growtopia', 'growtopia'),
('德谱', 'depu'),
('SoFi', 'sofi'),
('zenonia / 戰界', 'zenonia'),
('UMobile', 'umobile'),
('VITASOY', 'vitasoy'),
('360Kredi', '360kredi'),
('Garena', 'garena'),
('Ninjaz', 'ninjaz'),
('美柚', 'meiyou'),
('Ticket Plus', 'ticketplus'),
('Cosmart / 科斯玛特', 'cosmart'),
('Go Noodle House', 'gonoodle'),
('豆包MarsCode', 'marscode'),
('SayHi Chat', 'sayhichat'),
('Harry APP', 'harryapp'),
('USERJOY', 'userjoy'),
('goodniight', 'goodniight'),
('Empire88', 'empire88'),
('MEEFF', 'meeff'),
('FanShu', 'fanshu'),
('洋葱学园', 'yangcong'),
('DHL', 'dhl'),
('极光TV', 'jiguangtv'),
('jag-hk', 'jaghk'),
('Power Ship', 'powership'),
('WAUG', 'waug'),
('Shell Asia', 'shellasia'),
('Club 100', 'club100'),
('香港討論區', 'hkdiscuss'),
('Perya', 'perya'),
('职业培训网络平台', 'zhiyepx'),
('opinionworld', 'opinionworld'),
('MRG', 'mrg'),
('Sendo', 'sendo'),
('阅文集团', 'yuewen'),
('Vnptt', 'vnptt'),
('ClassPass', 'classpass'),
('悠悠优品 / youpin', 'youpin'),
('VIENDONG', 'viendong'),
('Peryagame', 'peryagame'),
('中国平安', 'pingan'),
('DCFever', 'dcfever'),
('GASH', 'gash'),
('ChoTot', 'chotot'),
('dito.ph', 'dito'),
('智联', 'zhilian'),
('抖音搜索', 'dysearch'),
('FunTown (戲谷)', 'funtown'),
('weed.th', 'weedth'),
('PlayTime', 'playtime'),
('Sparklive / Uplive', 'sparklive'),
('